// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hdgayvhdqaxbvlthditm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhkZ2F5dmhkcWF4YnZsdGhkaXRtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4ODA3NjQsImV4cCI6MjA2NDQ1Njc2NH0.b2t78R8zFubmmbh7gRArH0crV9JaB4HoajvUnJIrTk0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);